---

run:
  deadline: 5m

output:
  sort-results: true

linters:
  enable:
    - staticcheck
    - gofumpt
  disable-all: true

issues:
  max-same-issues: 0

linters-settings:
  gofumpt:
    extra-rules: true
